// Typegen: triggers ts-rs DTO export + generates the namespaced contract.ts from the utoipa OpenApi.
// Run via: cargo test -p api   (or: bun typegen)

use std::collections::{BTreeMap, BTreeSet};

use utoipa::OpenApi;

/// Map an OpenAPI schema JSON fragment to its TypeScript type string.
/// Tracks referenced schema names for the import line.
fn schema_to_ts(schema: &serde_json::Value, types: &mut BTreeSet<String>) -> Option<String> {
    if let Some(r#ref) = schema.get("$ref").and_then(|v| v.as_str()) {
        let name = r#ref.rsplit('/').next().unwrap_or(r#ref);
        types.insert(name.to_string());
        return Some(name.to_string());
    }
    if schema.get("type").and_then(|v| v.as_str()) == Some("array") {
        let inner = schema
            .get("items")
            .and_then(|i| schema_to_ts(i, types))
            .unwrap_or_else(|| "unknown".into());
        return Some(format!("{inner}[]"));
    }
    if let Some(one_of) = schema.get("oneOf").and_then(|v| v.as_array()) {
        let parts: Vec<String> = one_of
            .iter()
            .map(|s| {
                if s.get("type").and_then(|v| v.as_str()) == Some("null") {
                    "null".to_string()
                } else {
                    schema_to_ts(s, types).unwrap_or_else(|| "unknown".into())
                }
            })
            .collect();
        return Some(parts.join(" | "));
    }
    None
}

/// Extract path-param names from a path string like "/todos/{id}".
fn path_params(path: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut chars = path.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '{' {
            let name: String = chars.by_ref().take_while(|&c| c != '}').collect();
            if !name.is_empty() {
                out.push(name);
            }
        }
    }
    out
}

#[test]
fn export_contract() {
    // (operationId, METHOD, path, inputType, outputType)
    type Op = (String, String, String, String, String);
    let spec = serde_json::to_value(api::contract::ApiDoc::openapi()).unwrap();
    let paths = spec["paths"].as_object().unwrap();

    let mut grouped: BTreeMap<String, Vec<Op>> = BTreeMap::new();
    let mut types: BTreeSet<String> = BTreeSet::new();

    for (path, methods) in paths {
        for (method_lower, op) in methods.as_object().unwrap() {
            let tag = op["tags"][0].as_str().unwrap_or("default");
            let op_id = op["operationId"].as_str().unwrap();
            let method = method_lower.to_uppercase();

            // Params: from "parameters" array first, fallback to path string
            let mut params: Vec<String> = op["parameters"]
                .as_array()
                .map(|arr| {
                    arr.iter()
                        .filter(|p| p["in"].as_str() == Some("path"))
                        .map(|p| p["name"].as_str().unwrap().to_string())
                        .collect()
                })
                .unwrap_or_default();
            if params.is_empty() {
                params = path_params(path);
            }

            // Request body
            let req = op
                .pointer("/requestBody/content/application~1json/schema")
                .and_then(|s| schema_to_ts(s, &mut types));

            // Response: first 2xx
            let resp = op
                .get("responses")
                .and_then(|r| r.as_object())
                .and_then(|responses| {
                    responses
                        .iter()
                        .find(|(code, _)| code.starts_with('2'))
                        .and_then(|(_, resp)| {
                            resp.pointer("/content/application~1json/schema")
                                .and_then(|s| schema_to_ts(s, &mut types))
                        })
                });

            // Input type: path params object (+ request body type)
            let param_obj = (!params.is_empty())
                .then(|| format!("{{ {}: string }}", params.join(": string, ")));
            let input = match (param_obj, req) {
                (Some(p), Some(r)) => format!("{p} & {r}"),
                (Some(p), None) => p,
                (None, Some(r)) => r,
                (None, None) => "void".into(),
            };
            let output = resp.unwrap_or_else(|| "void".into());

            grouped.entry(tag.to_string()).or_default().push((
                op_id.into(),
                method,
                path.clone(),
                input,
                output,
            ));
        }
    }

    // Emit contract.ts
    let mut out = String::from("// GENERATED by typegen.rs — do not edit\n\n");
    let imports: Vec<String> = types.iter().cloned().collect();
    out.push_str(&format!(
        "import type {{ {} }} from \"./dto\";\n\n",
        imports.join(", ")
    ));
    out.push_str("interface Route<I = void, O = void> { method: string; path: string }\n");
    out.push_str("const route = <I = void, O = void>(method: string, path: string): Route<I, O> => ({ method, path });\n\n");
    out.push_str("export const contract = {\n");

    for (ns, routes) in &grouped {
        out.push_str(&format!("  {ns}: {{\n"));
        for (name, method, path, input, output) in routes {
            out.push_str(&format!(
                "    {name}: route<{input}, {output}>(\"{method}\", \"{path}\"),\n"
            ));
        }
        out.push_str("  },\n");
    }
    out.push_str(
        "} as const;\n\nexport type Contract = typeof contract;\nexport type { Route };\n",
    );

    std::fs::write("../web/src/lib/contract.ts", out).unwrap();
}
